name: CI

on:
  push:
    branches:
      - dev

jobs:
  compileAndUpload:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependences
      run: |
        npm install dotenv fs child-process path colors
    - name: Hello
      run: echo Hello !! Im gonna update the bot on development.
    - name: Current branch
      run: git branch
    - name: Current directory
      run: $PWD
    - name: Git configuration
      run: |
        git config --global user.email "leandro.cotti@widergy.com"
        git config --global user.name "lefcott19"
        git config --global core.safecrlf false
    - name: Installing AHK
      run: bots/commons/compiler/ahk-setup.exe /S
    - name: Compile bots and add files to git
      run: node scripts/updateBots :::changedScripts $(git diff-tree --no-commit-id --name-only -r HEAD -- bots/*-*/*.ahk)
    - name: List Modified files
      run: git status
    - name: Add files to Git
      run: git add .
    - name: Commit on dev
      run: git commit -am "Workflow Bot Commit"
    - name: Push to origin dev
      run: git push origin dev
